name: 'Release Environment Setup'
description: 'Sets up the environment for releasing the Waifu Motivator Plugin'
inputs:
  relase-type:
    description: 'The environment to set up for'
    required: true
    default: 'non-prod'
runs:
  using: 'node12'
  main: 'dist/index.js'
